config/routes.rb
Rails.application.routes.draw do
  get 'clips/create'
  get 'clips/destroy'
  #User
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'homes#top'
  get 'homes/about', to:'homes#about'
  get '/post/hashtag/:name', to: "posts#hashtag"
  get 'searchs/search', to:'searches#search'
  resources :vision_images, only: [:new, :create, :show]
  resources :relationships, only: [:create, :destroy]
  resources :users, only: [:show,:edit,:update] do
                    	member do
                    		get :hide
                    		patch :hide_update
                    		get :following, :followers
                    	end
  end
  resources :genres, only:[:show]
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]
  resources :posts, only: [:new,:create,:index,:show,:edit,:update, :destroy] do
    resource :clips, only: [:create, :destroy,]
    collection do
      get 'clips'
      get 'ranking'
      get 'get_genre_children', defaults: { format: 'json' }
    end
  	resource :favorites, only: [:create, :destroy]
  end

  #Admin
  devise_for :admins
    namespace :admins do
    root "homes#top"
    resources :users, only:[:index, :show, :edit, :update]
    resources :posts, only:[:index, :show, :edit, :update, :destroy] do
      collection do
        get 'genre_children', defaults: { format: 'json' }
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :image
  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :rooms, through: :entries

  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  #clip(ブックマーク)
  has_many :clips, dependent: :destroy
  has_many :clip_posts, through: :clips, source: :post

  def active_for_authentication?
    super && (self.user_status == false)
  end

  #フォロー機能
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    #logger.info(self.followings.include?(other_user))
    self.followings.include?(other_user)
  end

  #SNS認証googleログイン
  devise :omniauthable, omniauth_providers: %i[facebook twitter google_oauth2]
  # omniauthのコールバック時に呼ばれるメソッド
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
	def index
		@users = User.all.page(params[:page]).per(10)
	end
	def show
		@user = User.find(params[:id])
	end
	def edit
		@user = User.find(params[:id])
	end
	def update
		@user = User.find(params[:id])
		@user.update(user_params)
		redirect_to admins_user_path(@user)
	end

	private
	def user_params
		params.require(:user).permit(:image, :first_name, :last_name, :nick_name, :introduction, :email, :user_status)
	end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  # callback for facebook


  # callback for google
  def google_oauth2
    callback_for(:google)
  end

  # common callback method
  def callback_for(provider)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else
      session["devise.#{provider}_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
   #def new
     #super
   #end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!

	def show
		@user = User.find(params[:id])
		@posts = @user.posts.page(params[:page]).per(6)
			 if @user != current_user
				@posts = @user.posts.published.order("created_at DESC").page(params[:page]).per(6)
			end
		#google_map
		@hash = Gmaps4rails.build_markers(@posts) do |post, marker|
		      marker.lat post.latitude
		      marker.lng post.longitude
		      marker.infowindow post.title
		    end
		#DMページ
		@currentUserEntry = Entry.where(user_id: current_user.id)
		@userEntry = Entry.where(user_id: @user.id)
		if @user.id == current_user.id
		else
			@currentUserEntry.each do |cu|
				@userEntry.each do |u|
					if cu.room_id == u.room_id then
						@isRoom = true
						@roomId = cu.room_id
					end
				end
			end
			if @isRoom
			else
				@room = Room.new
				@entry = Entry.new
			end
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			flash[:notice]= 'ユーザー情報を編集しました'
			redirect_to user_path(@user)
		else
			render :edit
		end
	end

	def hide

	end

	def hide_update
		@user = current_user
		@user.update(user_status: true)
		reset_session
		redirect_to root_path
	end

	def following
		@user = User.find(params[:id])
		@users = @user.followings
		render 'show_follow'
	end

	def followers
		@user = User.find(params[:id])
		@users = @user.followers
		render 'show_follower'
	end

	private
	def user_params
		params.require(:user).permit(:first_name,:last_name,:nick_name,:introduction,:image,:user_status)
	end
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_stats.html.erb
<% user ||= current_user %>
<main style="display: flex;">
  <div>
      <%=link_to following_user_path(user) do %>
        <h5><strong id="followings" class="stat">
          <%= user.followings.count %>
        </strong>
        フォロー</h5>
      <% end %>
  </div>
  <div style="padding-left: 10px;">
      <%=link_to followers_user_path(user) do %>
        <h5><strong id="followers" class="stat">
          <%= user.followers.count %>
        </strong>
        フォロワー</h5>
      <% end %>
  </div>
</main>

app/views/users/edit.html.erb
<div class="container">
	<%= render 'layouts/errors', model: @user %>
	<div class="row">
		<div class="col-xs-10 col-xs-offset-1">

			<div class="row" style="margin-bottom: 50px;">
				<div class="col-xs-10 col-xs-offset-1">
				<h2>Mypage Edit</h2>
			</div>
			</div>

			<div class="row">
				<div class="col-xs-5">
					<%= form_for(@user) do |f| %>

						<div class="field">
							<%= attachment_image_tag(@user, :image, size:'200x200', fallback: "no_image.jpg") %>
							<%= f.attachment_field :image, class: "user_image" %>
						</div>
				</div>
				<div class="col-xs-5">
						<div class="field row" style="margin-bottom: 15px;">
							<%= f.label :first_name, class: "col-xs-4" %>
							<%= f.text_field :first_name, class: "col-xs-5 first_name" %>
						</div>
						<div class="field row" style="margin-bottom: 15px;">
							<%= f.label :last_name, class: "col-xs-4" %>
							<%= f.text_field :last_name, class: "col-xs-5 last_name" %>
						</div>
						<div class="field row" style="margin-bottom: 15px;">
							<%= f.label :nick_name, class: "col-xs-4" %>
							<%= f.text_field :nick_name, class: "col-xs-5 nick_name" %>
						</div>
						<div class="field row" style="margin-bottom: 15px;">
							<%= f.label :introduction, class: "col-xs-4" %>
							<%= f.text_area :introduction, class: "col-xs-5 introduction" %>
						</div>
						<div class="field row" style="margin-bottom: 15px;">
							<%= f.label :email, class: "col-xs-4" %>
							<%= f.text_field :email, class: "col-xs-5 email" %>
						</div>
						<div class="row" style="margin-top: 40px;">
							<div class="col-xs-12">
								<div class="pull-left">
									<%= f.submit '変更を保存する', class: "btn btn-primary" %>
								</div>
								<div class="pull-right">
									<%= link_to '退会する', hide_user_path, class: "btn btn-danger"%>
								</div>
							</div>
						</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/users/hide.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">


			<h3 class="text-center">本当に退会しますか？</h3>

		</div>
	</div>
</div>
<br>
<br>

<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">


			<p class="text-center">退会すると、会員登録情報や<br>
			これまでの投稿履歴が観覧できなくなります。<br>
			退会するには、「退会する」をクリックしてください。</p>

		</div>
	</div>
</div>

<br>


<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<p class="text-center">

		<%= link_to ' 退会しない', user_path, class: "btn btn-primary" %>

		<%= link_to "退会する", hide_update_user_path(current_user), method: :patch, "data-confirm" => "本当に退会しますか？", class: "btn btn-danger" %>

			</p>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">

			<!-- ユーザー情報 -->
			<div class="row" style="margin-left: 10px;">
				<%= attachment_image_tag(@user, :image, size:'100x100', class: "img-circle", fallback: "no_image.jpg") %>
			</div>
			<div class="row" style="margin-top: 10px;">
				<strong><%= @user.nick_name %></strong>
			</div>
			<div class="row" style="margin-top: 10px;">
				<strong><%= @user.introduction %></strong>
			</div>
			<div class="row" style="margin-top: 15px;"><!--フォロー情報-->
				<%= render 'users/stats', user: @user %>
			</div>
			<div class="row" style="margin-bottom: 10px;"><!--フォロー情報-->
				<%= render 'relationships/follow_button', user: @user %>
			</div>
			<div class="row">
				<div class="col-xs-8" style="padding-top: 15px; border-top: 1px solid silver;">
					<div class="row">
						<% if @user.id == current_user.id %>
							<%= link_to rooms_path do %>
								<i class="far fa-envelope fa-x"></i> DM一覧
							<% end %>
						<% else %>
							<% if @isRoom == true %>
							    <a href="/rooms/<%= @roomId %>">
							    	<i class="fas fa-paper-plane fa-x"></i> DM内容を見る
							    </a>
							<% else %>
							    <%= form_for @room do |f| %>
							      <%= fields_for @entry do |e| %>
							        <%= e.hidden_field :user_id, :value=> @user.id %>
							      <% end %>
							    　<button type="submit" style="background-color: transparent;border: none;cursor: pointer;outline: none;padding: 0;appearance: none;"><i class="fas fa-paper-plane fa-x"></i> DMを送る
							      </button>
								<% end %>
							<% end %>
						<% end %>
					</div>
					<!-- 表示の制限 -->
					<% if @user == current_user %>
					<div class="row">
						<%=link_to edit_user_path, data: {"turbolinks" => false}  do %>
							<i class="fas fa-user-edit fa-x"></i> マイページ編集
						<% end %>
					</div>
					<div class="row">
						<%=link_to new_post_path, data: {"turbolinks" => false} do %>
						<i class="fas fa-plus-circle fa-x"></i> 新規投稿
						<% end %>
					</div>
					<div class="row">
						<%=link_to clips_posts_path, data: {"turbolinks" => false} do %>
						<i class="far fa-bookmark fa-x"></i> お気に入り一覧
						<% end %>
					</div>
					<% end %>
				</div>
			</div>
		</div>

		<div class="col-xs-9">
			<div class="row">
				<!-- Google Map -->
				<div style="width: 100%;">
  					<div id="map" style="width: 100%; height: 300px;"></div>
				</div>
				<script>
				  handler = Gmaps.build('Google');
				  handler.buildMap({
				    provider: {mapTypeId: 'roadmap'},
				    internal: {id: 'map'}
				    },
				    function(){
				    //markers = handler.addMarkers(#{raw @hash.to_json})
				    markers = handler.addMarkers(<%=raw @hash.to_json %>)
				    handler.bounds.extendWith(markers);
				    handler.fitMapToBounds();
				    handler.getMap().setCenter(new google.maps.LatLng(35.681298, 139.7640582));
				    handler.getMap().setZoom(1);
				  });
				</script>
			</div>
			<!-- ユーザーの投稿一覧 -->
			<div class="row" style="padding-top: 50px;">
				<% @posts.each do |post| %>
					<div class="col-xs-4">
						<div class="user-post-box">
							<div class="row" style="margin-top: 20px;">
								<div class="col-xs-12">
									<% if post.post_images.present? %>
										<% post.post_images.first(1).each do |image| %>
											<%= link_to post_path(post.id) do %>
												<%= attachment_image_tag image, :image, size:'250x200', fallback: "no_image.jpg", class: "user-post-img" %>
											<% end %><!--scssで指定 -->
										<% end %>
									<% end %>
								</div>
							</div>
							<div class="row" style="margin-top: 20px;">
								<div class="col-xs-12">
									<i class="fas fa-map-marker-alt"></i>  <%= link_to post.title,post, class: "post_#{post.id}" %>
								</div>
							</div>
							<div class="row" style="margin-bottom: 20px;">
								<div class="col-xs-12">
									<% if @user.id == current_user.id %>
										<% if post.status_before_type_cast == 0 %>
											<p>下書き</p>
										<% else %>
											<p>公開中</p>
										<% end %>
									<% end %>
								</div>
							</div>
						</div>
					</div>
				<% end %>
			</div>
			<div class="row pull-right">
			<%= paginate @posts %>
			</div>
		</div>
	</div>
</div>

app/views/users/show_follow.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-8 col-xs-offset-2">
			<h2>Follow Users</h2>
			<table class="table">
				<thead>
					<tr>
						<th>image</th>
						<th>Name</th>
						<th>Introduction</th>
					</tr>
				</thead>

				<tbody>
                    <% @user.followings.each do |user| %>
		                <tr>
		                	<td>
		                		<%= link_to user_path(user) do %>
		                			<%= attachment_image_tag(user, :image, size:'50x50', fallback: "no_image.jpg") %>
	                			<% end %>
		                	</td>
			                <td><%= user.nick_name %></td>
			                <td><%= user.introduction %></td>
			                
			                <td><% unless current_user == user %>

	                        		<%if current_user.following?(user) %>
			                            <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: {method: :delete }) do |f| %>
			                               <%= hidden_field_tag :follow_id, user.id %>
			                               <%= f.submit 'Unfollow', class: 'btn btn-danger btn-block' %>
			                            <% end %>
	                        		<% else %>
			                            <%= form_for(current_user.relationships.build) do |f| %>
			   	                           <%= hidden_field_tag :follow_id, user.id %>
			   	                           <%= f.submit 'Follow', class: 'btn btn-primary btn btn-block' %>
			                        	<% end %>
	                        		<% end %>
                        		<% end %>
	                        </td>
		                </tr>
	                <% end %>
	            </tbody>
            </table>
       </div>
   </div>
</div>

app/views/users/show_follower.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-8 col-xs-offset-2">
			<h2>Follower Users</h2>
  			<table class="table">
  				<thead>
  					<tr>
  						<th>image</th>
  						<th>Name</th>
  						<th>Introduction</th>
  					</tr>
  				</thead>

          <tbody>
            <% @user.followers.each do |user| %>
              <tr>
                <td>
                    <%= link_to user_path(user) do %>
                      <%= attachment_image_tag(user, :image, size:'50x50', fallback: "no_image.jpg") %>
                    <% end %>
                </td>
                <td><%= user.nick_name %></td>
                <td><%= user.introduction %></td>
  	            
  	            <td><% unless current_user == user %>
                        <%if current_user.following?(user) %>
                            <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: {method: :delete }) do |f| %>
                               <%= hidden_field_tag :follow_id, user.id %>
                               <%= f.submit 'Unfollow', class: 'btn btn-danger btn-block' %>
                            <% end %>
                        <% else %>
                            <%= form_for(current_user.relationships.build) do |f| %>
   	                           <%= hidden_field_tag :follow_id, user.id %>
   	                           <%= f.submit 'Follow', class: 'btn btn-primary btn btn-block' %>
                        	   <% end %>
                        <% end %>
                    <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
   </div>
</div>