config/routes.rb
Rails.application.routes.draw do
  get 'clips/create'
  get 'clips/destroy'
  #User
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'homes#top'
  get 'homes/about', to:'homes#about'
  get '/post/hashtag/:name', to: "posts#hashtag"
  get 'searchs/search', to:'searches#search'
  resources :vision_images, only: [:new, :create, :show]
  resources :relationships, only: [:create, :destroy]
  resources :users, only: [:show,:edit,:update] do
                    	member do
                    		get :hide
                    		patch :hide_update
                    		get :following, :followers
                    	end
  end
  resources :genres, only:[:show]
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]
  resources :posts, only: [:new,:create,:index,:show,:edit,:update, :destroy] do
    resource :clips, only: [:create, :destroy,]
    collection do
      get 'clips'
      get 'ranking'
      get 'get_genre_children', defaults: { format: 'json' }
    end
  	resource :favorites, only: [:create, :destroy]
  end

  #Admin
  devise_for :admins
    namespace :admins do
    root "homes#top"
    resources :users, only:[:index, :show, :edit, :update]
    resources :posts, only:[:index, :show, :edit, :update, :destroy] do
      collection do
        get 'genre_children', defaults: { format: 'json' }
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :image
  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :rooms, through: :entries

  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  #clip(ブックマーク)
  has_many :clips, dependent: :destroy
  has_many :clip_posts, through: :clips, source: :post

  def active_for_authentication?
    super && (self.user_status == false)
  end

  #フォロー機能
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    #logger.info(self.followings.include?(other_user))
    self.followings.include?(other_user)
  end

  #SNS認証googleログイン
  devise :omniauthable, omniauth_providers: %i[facebook twitter google_oauth2]
  # omniauthのコールバック時に呼ばれるメソッド
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
	def index
		@users = User.all.page(params[:page]).per(10)
	end
	def show
		@user = User.find(params[:id])
	end
	def edit
		@user = User.find(params[:id])
	end
	def update
		@user = User.find(params[:id])
		@user.update(user_params)
		redirect_to admins_user_path(@user)
	end

	private
	def user_params
		params.require(:user).permit(:image, :first_name, :last_name, :nick_name, :introduction, :email, :user_status)
	end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  # callback for facebook


  # callback for google
  def google_oauth2
    callback_for(:google)
  end

  # common callback method
  def callback_for(provider)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else
      session["devise.#{provider}_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
   #def new
     #super
   #end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!

	def show
		@user = User.find(params[:id])
		@posts = @user.posts.page(params[:page]).per(6)
			 if @user != current_user
				@posts = @user.posts.published.order("created_at DESC").page(params[:page]).per(6)
			end
		#google_map
		@hash = Gmaps4rails.build_markers(@posts) do |post, marker|
		      marker.lat post.latitude
		      marker.lng post.longitude
		      marker.infowindow post.title
		    end
		#DMページ
		@currentUserEntry = Entry.where(user_id: current_user.id)
		@userEntry = Entry.where(user_id: @user.id)
		if @user.id == current_user.id
		else
			@currentUserEntry.each do |cu|
				@userEntry.each do |u|
					if cu.room_id == u.room_id then
						@isRoom = true
						@roomId = cu.room_id
					end
				end
			end
			if @isRoom
			else
				@room = Room.new
				@entry = Entry.new
			end
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			flash[:notice]= 'ユーザー情報を編集しました'
			redirect_to user_path(@user)
		else
			render :edit
		end
	end

	def hide

	end

	def hide_update
		@user = current_user
		@user.update(user_status: true)
		reset_session
		redirect_to root_path
	end

	def following
		@user = User.find(params[:id])
		@users = @user.followings
		render 'show_follow'
	end

	def followers
		@user = User.find(params[:id])
		@users = @user.followers
		render 'show_follower'
	end

	private
	def user_params
		params.require(:user).permit(:first_name,:last_name,:nick_name,:introduction,:image,:user_status)
	end
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/users/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-10 col-xs-offset-1">
			<h2>ユーザー情報編集</h2>

			<%= form_for(@user,url:admins_user_path) do |f| %>
				<div class="row" style="margin-top: 40px;">
					<div class="col-xs-3">
						<div class="field">
							<%= attachment_image_tag(@user, :image, id: "preview", size:'200x200', fallback: "no_image.jpg") %>
							<%= f.attachment_field :image, id: :item_img, class: "user_image" %>
						</div>
					</div>

					<div class="col-xs-6 col-xs-offset-3">
						<div class="field row" style="margin-bottom: 15px;">
							<%= f.label :first_name, class: "col-xs-4" %>
							<%= f.text_field :first_name, class: "col-xs-5 first_name" %>
						</div>
						<div class="field row" style="margin-bottom: 15px;">
							<%= f.label :last_name, class: "col-xs-4" %>
							<%= f.text_field :last_name, class: "col-xs-5 last_name" %>
						</div>
						<div class="field row" style="margin-bottom: 15px;">
							<%= f.label :nick_name, class: "col-xs-4" %>
							<%= f.text_field :nick_name, class: "col-xs-5 nick_name" %>
						</div>
						<div class="field row" style="margin-bottom: 15px;">
							<%= f.label :introduction, class: "col-xs-4" %>
							<%= f.text_area :introduction, class: "col-xs-5 introduction" %>
						</div>
						<div class="field row" style="margin-bottom: 15px;">
							<%= f.label :email, class: "col-xs-4" %>
							<%= f.text_field :email, class: "col-xs-5 email" %>
						</div>
						<div class="row", style="padding-top: 8px;">	
						    <%= f.radio_button :user_status, :false %>有効
			    			<%= f.radio_button :user_status, :true %>退会済み
		    			</div>
						<div class="row" style="margin-top: 20px;">
							<div class="col-xs-4">
								<%= f.submit '変更を保存する', class: "btn btn-primary" %>
							</div>
							<div class="col-xs-4">
								<%= link_to 'ユーザー詳細に戻る', admins_user_path, class: "btn btn-info" %>
							</div>
						</div>
					</div>
					<% end %>

		</div>
	</div>
</div>

app/views/admins/users/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-10 col-xs-offset-1">

			<div class="row">
				<h2>ユーザー　一覧</h2>
			</div>

				<% @users.each do |user| %>
				<div class="row" style="margin-top: 30px; padding-bottom: 20px; border-bottom: 1px solid; border-color: silver;">
					<div class="col-xs-4">
						<%= link_to admins_user_path(user.id) do %>
							<%= attachment_image_tag(user, :image, size:'60x60', fallback: "no_image.jpg") %>
						<% end %>
					</div>
					<div class="col-xs-4">
						<%= user.nick_name %>
					</div>
					<div class="col-xs-4">
						<%= user.email %>
					</div>
				</div>
				<% end %>
				<div class="row pull-right">
				<%= paginate @users %>
				</div>
		</div>
	</div>
</div>

app/views/admins/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-10 col-xs-offset-1">

			<h2>ユーザー詳細</h2>

				<div class="row" style="margin-top: 30px;">
					<div class="col-xs-2">
						ユーザーID : <%= @user.id %>
					</div>
					<div class="col-xs-4">
						<strong><%= @user.first_name %>
						<%= @user.last_name %></strong>
					</div>
					<div class="col-xs-2">
						<%if @user.user_status == false %>
							<p style="border: 1px solid; border-radius: 30px; text-align: center; background-color: skyblue;">有効会員</p>
						<% else %>
							<p style="border: 1px solid; border-radius: 30px; text-align: center; background-color: tomato;">退会済</p>
						<% end %>
					</div>
				</div>

				<div class="row" style="margin-top: 50px;">
					<div class="col-xs-4">
						<%= attachment_image_tag(@user, :image, size:'200x200') %>
					</div>
					<div class="col-xs-6 col-xs-offset-2">
						<div class="row">
							<h3>user_name </h3> <%= @user.nick_name %>
						</div>
						<div class="row">
							<h3>Introduction </h3> <%= @user.introduction %>
						</div>
						<div class="row">
							<h3>Email </h3> <%= @user.email %>
						</div>
					</div>
				</div>
				<div class="row" style="margin-top: 30px;">
					<div class="col-xs-6 col-xs-offset-3 pull-right">
						<div class="row">
							<div class="col-xs-4">
								<%= link_to '編集する', edit_admins_user_path, class: "btn btn-primary pull-right", data: {"turbolinks" => false} %>
							</div>
							<div class="col-xs-4">
								<%= link_to 'ユーザー一覧に戻る', admins_users_path, class: "btn btn-info" %>
							</div>
						</div>
					</div>
				</div>


		</div>
	</div>
</div>