config/routes.rb
Rails.application.routes.draw do
  get 'clips/create'
  get 'clips/destroy'
  #User
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'homes#top'
  get 'homes/about', to:'homes#about'
  get '/post/hashtag/:name', to: "posts#hashtag"
  get 'searchs/search', to:'searches#search'
  resources :vision_images, only: [:new, :create, :show]
  resources :relationships, only: [:create, :destroy]
  resources :users, only: [:show,:edit,:update] do
                    	member do
                    		get :hide
                    		patch :hide_update
                    		get :following, :followers
                    	end
  end
  resources :genres, only:[:show]
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]
  resources :posts, only: [:new,:create,:index,:show,:edit,:update, :destroy] do
    resource :clips, only: [:create, :destroy,]
    collection do
      get 'clips'
      get 'ranking'
      get 'get_genre_children', defaults: { format: 'json' }
    end
  	resource :favorites, only: [:create, :destroy]
  end

  #Admin
  devise_for :admins
    namespace :admins do
    root "homes#top"
    resources :users, only:[:index, :show, :edit, :update]
    resources :posts, only:[:index, :show, :edit, :update, :destroy] do
      collection do
        get 'genre_children', defaults: { format: 'json' }
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/clip.rb
class Clip < ApplicationRecord
	belongs_to :user
	belongs_to :post
	validates :user_id, uniqueness: { scope: :post_id }
end

app/models/entry.rb
class Entry < ApplicationRecord
	belongs_to :user
	belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :posts, dependent: :destroy
	has_ancestry
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
	validates :hashname, presence: true, length: {maximum:99}
	has_many :post_hashtag
	has_many :posts, through: :post_hashtag
end

app/models/landmark.rb
class Landmark < ApplicationRecord
	belongs_to :vision_image
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :user
	belongs_to :room

	attachment :image

	validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user, foreign_key: 'user_id'

	enum status:{ draft: 0, published: 1 }
	has_many :favorites, dependent: :destroy
	#画像複数投稿
	has_many :post_images, dependent: :destroy
	accepts_attachments_for :post_images, attachment: :image
	#hash_tag
	has_many :post_hashtag, dependent: :destroy
	has_many :hashtags, through: :post_hashtag
	belongs_to :genre, optional: true
	#google_map
	geocoded_by :title
	after_validation :geocode
	#clip(ブックマーク)
	has_many :clips, dependent: :destroy

	#バリデーション
	validates :title, presence: true
	validates :body, presence: true
	validates :rate, presence: true
	validates :genre_id, presence: true
  	validates :genre, presence: true, if: -> { genre_id.present? }
  	validates :post_images_images, presence: true

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

	#ハッシュタグ
	after_create do
		post = Post.find_by(id: self.id)
		hashtags = self.body.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
		hashtags.uniq.map do |hashtag|
			#ハッシュタグは先頭の'#'を外した上で保存
			tag = Hashtag.find_or_create_by(hashname: hashtag.downcase.delete('#'))
			PostHashtag.create(post_id: post.id, hashtag_id: tag.id)
		end
	end

	before_update do
    	PostHashtag.where(post_id: self.id).destroy_all
		hashtags = self.body.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
		hashtags.uniq.map do |hashtag|
			tag = Hashtag.find_or_create_by(hashname: hashtag.downcase.delete('#'))
			PostHashtag.create(post_id: self.id, hashtag_id: tag.id)
		end
	end

	#ブックマーク
	def clip_by?(user)
		clips.where(user_id: user.id).exists?
	end

end

app/models/post_hashtag.rb
class PostHashtag < ApplicationRecord
  belongs_to :post
  belongs_to :hashtag
  validates  :post_id, presence: true
  validates  :hashtag_id,   presence: true
end

app/models/post_image.rb
class PostImage < ApplicationRecord
	belongs_to :post, optional: true
	attachment :image
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :user
	belongs_to :follow, class_name: 'User'

	validates :user_id, presence: true
	validates :follow_id, presence:true
end

app/models/room.rb
class Room < ApplicationRecord
	has_many :messages, dependent: :destroy
	has_many :entries, dependent: :destroy
	has_many :users, through: :entries
	attachment :image

	def partner(user)
		#自分以外のエントリーを返す
		if user == entries.first.user
			entries.second.user
		else
			entries.first.user
		end
	end
end

app/models/tag.rb
class Tag < ApplicationRecord
	belongs_to :vision_image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :image
  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :rooms, through: :entries

  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  #clip(ブックマーク)
  has_many :clips, dependent: :destroy
  has_many :clip_posts, through: :clips, source: :post

  def active_for_authentication?
    super && (self.user_status == false)
  end

  #フォロー機能
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    #logger.info(self.followings.include?(other_user))
    self.followings.include?(other_user)
  end

  #SNS認証googleログイン
  devise :omniauthable, omniauth_providers: %i[facebook twitter google_oauth2]
  # omniauthのコールバック時に呼ばれるメソッド
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

end

app/models/vision_image.rb
class VisionImage < ApplicationRecord
	attachment :image
	has_many :tags, dependent: :destroy
	has_many :landmarks, dependent: :destroy

	validates :image, presence: true
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
	before_action :authenticate_user!

	def create
		@room = Room.create
		@entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)
		@entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
    	redirect_to "/rooms/#{@room.id}"
	end

	def show
	  @room = Room.find(params[:id])
	  if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
	      @messages = @room.messages
	      @message = Message.new
	      @partner = @room.partner(current_user)
	  else
	      redirect_back(fallback_location: root_path)
	  end
	end

	def index
		@response = []
		my_entries = Entry.where(user_id: current_user.id)
		my_entries.each do |entry|
			room_info_for_response = {}
			room_info_for_response[:room] = entry.room.id
			room_info_for_response[:partner] = Entry.where(room_id: entry.room.id).where.not(user_id: current_user.id)[0].user
			room_info_for_response[:latest_message] = Message.where(room_id: entry.room.id).last
			@response << room_info_for_response
		end
	end
end

app/helpers/clips_helper.rb
module ClipsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	def render_with_hashtags(body)
		body.gsub(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/){|word| link_to word, "/post/hashtag/#{word.delete("#")}"}.html_safe
	end
end

app/helpers/rooms_helper.rb
module RoomsHelper

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/rooms/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-8 col-xs-offset-2">
			<table class="table">
			  	<thead>
			  		<tr>
			  			<td><strong>icon</strong></td>
			  			<td><strong>User name</strong></td>
			  			<td><strong>Latest message</strong></td>
			  		</tr>
			  	</thead>
			  	<tbody>
					<% @response.each do |response| %>
				  		<tr>
				  			<td>
				  				<%= link_to room_path(response[:room]) do %>
		  							<%= attachment_image_tag(response[:partner], :image, size:'50x50', class: "img-circle", fallback: "no_image.jpg") %>
		  						<% end %>
		  					</td>
						  	<td><strong>User:</strong> <%= response[:partner].nick_name %>
						  	</td>
						  	<td><strong>Message:</strong> <%= response[:latest_message]&.content %>
						  	</td>
					    </tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/rooms/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="row">
        <div class="col-xs-4">
          <div class="user-box">
            <div class="user-box-title">
              <%= link_to user_path(@partner.id) do %>
              <%= @partner.nick_name%>さん
              <% end %>とのメッセージ
            </div>
            <div class="user-box-body">
              <div class="row">
                <%= attachment_image_tag(@partner, :image, size:'100x100', class: "img-circle", fallback: "no_image.jpg") %>
              </div>
              <div class="row" style="margin-top: 10px;">
                <strong>nick_name : </strong><%= @partner.nick_name %>
              </div>
              <div class="row" style="margin-top: 10px;">
                <strong>introduction : </strong><%= @partner.introduction %>
              </div>
              <div class="row" style="margin-top: 15px;"><!--フォロー情報-->
                <%= render 'users/stats', user: @user %>
              </div>
            </div>
          </div>
          <%= link_to 'DM一覧に戻る', rooms_path, class: "btn btn-primary" %>
          <%= link_to 'マイページに戻る', user_path(current_user), class: "btn btn-info" %>
        </div>
        <div class="col-xs-1">
        </div>
        <div class="col-xs-6">
            <% if @messages.present? %>
              <% @messages.each do |m| %>
                <% if m.user.nick_name == current_user.nick_name %>
                    <div class="row">
                      <div class="message pull-right">
                        <div class="mycomment">
                            <h5><%= m.content %></h5>
                        </div>
                      </div>
                    </div>
                <% else %>
                    <div class="row">
                      <div class="balloon">
                        <div class="faceicon">
                          <%= link_to user_path(m.user.id) do %>
                            <%= attachment_image_tag(m.user, :image, size:'40x40', class: "img-circle", fallback: "no_image.jpg") %>
                          <% end %>
                        </div>
                        <div class="chat">
                          <div class="says">
                            <h5><%= m.content %></h5>
                          </div>
                        </div>
                      </div>
                    </div>
                <% end %>
              <% end %>
            <% else %>
              <h3 class="text-center">メッセージはまだありません</h3>
            <% end %>
            <%= render 'layouts/errors', model: @message %>
            <div class="row" style="margin-top: 50px;">
            <%= form_for @message do |f| %>
              <%= f.text_area :content, :placeholder => "-- メッセージを入力して下さい --", class: "col-xs-12 dm-body" %>
              <%= f.hidden_field :room_id, :value => @room.id %>
              <%= button_tag '', :type => "submit", class: "dm-submit pull-right" do %>
               <i class="fas fa-paper-plane" style="color: #fff;"></i>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>