config/routes.rb
Rails.application.routes.draw do
  get 'clips/create'
  get 'clips/destroy'
  #User
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'homes#top'
  get 'homes/about', to:'homes#about'
  get '/post/hashtag/:name', to: "posts#hashtag"
  get 'searchs/search', to:'searches#search'
  resources :vision_images, only: [:new, :create, :show]
  resources :relationships, only: [:create, :destroy]
  resources :users, only: [:show,:edit,:update] do
                    	member do
                    		get :hide
                    		patch :hide_update
                    		get :following, :followers
                    	end
  end
  resources :genres, only:[:show]
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]
  resources :posts, only: [:new,:create,:index,:show,:edit,:update, :destroy] do
    resource :clips, only: [:create, :destroy,]
    collection do
      get 'clips'
      get 'ranking'
      get 'get_genre_children', defaults: { format: 'json' }
    end
  	resource :favorites, only: [:create, :destroy]
  end

  #Admin
  devise_for :admins
    namespace :admins do
    root "homes#top"
    resources :users, only:[:index, :show, :edit, :update]
    resources :posts, only:[:index, :show, :edit, :update, :destroy] do
      collection do
        get 'genre_children', defaults: { format: 'json' }
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user, foreign_key: 'user_id'

	enum status:{ draft: 0, published: 1 }
	has_many :favorites, dependent: :destroy
	#画像複数投稿
	has_many :post_images, dependent: :destroy
	accepts_attachments_for :post_images, attachment: :image
	#hash_tag
	has_many :post_hashtag, dependent: :destroy
	has_many :hashtags, through: :post_hashtag
	belongs_to :genre, optional: true
	#google_map
	geocoded_by :title
	after_validation :geocode
	#clip(ブックマーク)
	has_many :clips, dependent: :destroy

	#バリデーション
	validates :title, presence: true
	validates :body, presence: true
	validates :rate, presence: true
	validates :genre_id, presence: true
  	validates :genre, presence: true, if: -> { genre_id.present? }
  	validates :post_images_images, presence: true

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

	#ハッシュタグ
	after_create do
		post = Post.find_by(id: self.id)
		hashtags = self.body.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
		hashtags.uniq.map do |hashtag|
			#ハッシュタグは先頭の'#'を外した上で保存
			tag = Hashtag.find_or_create_by(hashname: hashtag.downcase.delete('#'))
			PostHashtag.create(post_id: post.id, hashtag_id: tag.id)
		end
	end

	before_update do
    	PostHashtag.where(post_id: self.id).destroy_all
		hashtags = self.body.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
		hashtags.uniq.map do |hashtag|
			tag = Hashtag.find_or_create_by(hashname: hashtag.downcase.delete('#'))
			PostHashtag.create(post_id: self.id, hashtag_id: tag.id)
		end
	end

	#ブックマーク
	def clip_by?(user)
		clips.where(user_id: user.id).exists?
	end

end

app/controllers/admins/posts_controller.rb
class Admins::PostsController < ApplicationController
	before_action :set_genre_parent, only:[:new, :create, :edit, :update]

	def index
		@posts = Post.all.page(params[:page]).per(9)
	end
	def show
		@post = Post.find(params[:id])
	end
	def edit
		@post = Post.find(params[:id])
	end
	def genre_children #親カテゴリーが選択された後に動くアクション
		@genre_children = Genre.find_by(id: "#{params[:parent_name]}", ancestry: nil).children
	end
	def update
		@post = Post.find(params[:id])
		@post.update(post_params)
		redirect_to admins_post_path
	end
	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to admins_posts_path
	end

	private
	def post_params
		params.require(:post).permit(:title, :body, :rate, :genre_id, :status, post_images_images: [] )
	end
	def set_genre_parent
		@genre_parent_array = [{ name: "--", id: "--"}] #親カテゴリーのみ抽出、配列
			Genre.where(ancestry: nil).each do |parent|
				@genre_parent_array << { name: parent.name, id: parent.id}
			end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :correct_user, only:[:edit]
	before_action :set_genre_parent, only:[:new, :create, :edit, :update]
	before_action :authenticate_user!, only: [:new, :get_genre_children, :create, :clips, :edit, :update, :destroy]

	def new
		@post = Post.new
		@post.post_images.build
		#下書き一覧
		@posts = Post.draft.where(:user_id => current_user.id).order("created_at DESC")
	end
	def get_genre_children #親カテゴリーが選択された後に動くアクション
		@genre_children = Genre.find_by(id: "#{params[:parent_name]}", ancestry: nil).children
	end

	def create
		@post = Post.new(post_params)
		@post.user_id = current_user.id
		@user = current_user
		if @post.save
			flash[:notice]= '投稿に成功しました'
			redirect_to post_path(@post)
		else
			@post.post_images.build
			#下書き保存
			@posts = Post.draft.where(:user_id => current_user.id).order("created_at DESC")
			render :new
		end
	end

	def hashtag #ハッシュタグ
		@user = current_user
		@tag = Hashtag.find_by(hashname: params[:name])
		@posts = []
		PostHashtag.where(hashtag_id: @tag.id).includes(:post).each do |post_hashtag|
			@posts << post_hashtag.post
		end
	end

	def index
		@posts = Post.published.order("created_at DESC")
		             .joins(:user)
					 .where(users: {user_status: false}).page(params[:page]).per(6)
		@parents = Genre.where(ancestry: nil)
		@tag = Hashtag.all.order("created_at DESC")
	end

	def ranking #ランキング
		@all_ranks = Post.find(Favorite.group(:post_id).order('count(post_id) desc')
					 .limit(10).pluck(:post_id))
		@parents = Genre.where(ancestry: nil)
	end

	def clips #ブックマーク
		@posts = current_user.clip_posts.includes(:user).page(params[:page]).per(6)
		#google_map
		@hash = Gmaps4rails.build_markers(@posts) do |post, marker|
		      marker.lat post.latitude
		      marker.lng post.longitude
		      marker.infowindow post.title
		    end
	end

	def show
		@post = Post.find_by(id: params[:id])
		#google_map
		@hash = Gmaps4rails.build_markers(@post) do |post, marker|
		      marker.lat post.latitude
		      marker.lng post.longitude
		      marker.infowindow post.title
		    end

		if @post.nil?
			redirect_to root_path
		elsif @post.draft?
			login_required
		end
	end

	def login_required
		redirect_to user_session_path unless current_user
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		if  @post.update(post_params)
			flash[:notice]= '投稿を編集しました'
		    redirect_to @post
		else
			render :edit
		end
	end

	def destroy
		@post = Post.find(params[:id])
		if @post.destroy
			redirect_to posts_path
		else
			flash[:notice]= 'deleted post successfully.'
			render 'show'
		end
	end

	private
	def post_params
		params.require(:post).permit(:title, :body, :rate, :status, :latitude, :longitude, :genre_id, post_images_images: [])
	end

	def correct_user
		@post = Post.find(params[:id])
		if @post.user != current_user
			redirect_to posts_path
		end
	end

	def set_genre_parent
		@genre_parent_array = [{ name: "--", id: "--"}] #親カテゴリーのみ抽出、配列
			Genre.where(ancestry: nil).each do |parent|
				@genre_parent_array << { name: parent.name, id: parent.id}
			end
	end

end

app/helpers/admins/posts_helper.rb
module Admins::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	def render_with_hashtags(body)
		body.gsub(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/){|word| link_to word, "/post/hashtag/#{word.delete("#")}"}.html_safe
	end
end

app/views/posts/_clip.html.erb
<%= link_to post_clips_path(post.id), method: :post, id: :"js-clip-button-for-post-#{post.id}" do %>
	<i class="far fa-bookmark fa-2x"></i>
<% end %>

app/views/posts/_confirm.html.erb
<% posts.each do |post| %>
	<div class="col-xs-4" style="margin-top: 20px;">

		<div class="row" style="margin: 10px;">
			<div class="col-xs-12">
				<% post.post_images.first(1).each do |image| %>
					<%= link_to edit_post_path(post.id) do %>
						<%= attachment_image_tag(image, :image, size:'220x200', class: "scale-img") %>
					<% end %>
				<% end %>
			</div>
		</div>
		<div class="row" style="margin: 10px;">
			<div class="col-xs-8" style="padding-top: 10px; padding-right: 0; margin: 0;">
				<div id="star-rate-<%= post.id %>"></div>
			</div>
			<div class="col-xs-2" style="color:silver; padding: 0; margin:0;">
				<h4 class="mb-3"><%= post.rate %></h4>
			</div>
	        <script>
	        	$('#star-rate-<%= post.id %>').raty({
		            size: 36,
		            starOff:  '<%= asset_path('star-off.png') %>',
		            starOn : '<%= asset_path('star-on.png') %>',
		            starHalf: '<%= asset_path('star-half.png') %>',
		            half: true,
		            readOnly: true,
		            score: <%= post.rate %>,
	     		 });
	        </script>
        </div>
		<div class="row" style="margin: 10px;">
			<div class="col-xs-12">
				<strong>Title: </strong><%= post.title %>
			</div>
		</div>
	</div>
<% end %>

app/views/posts/_new_form.html.erb
<%= form_for(post) do |f| %>
	<div class="field" style="margin-bottom: 20px;">
		<% post.post_images.each do |image| %>
			<%= attachment_image_tag(image, :image, id: "preview", size:'220x200', fallback: "no_image.jpg") %>
		<% end %>
		<%= f.attachment_field :post_images_images, id: :item_img, multiple: true%>
	</div>
	<div class="field row" id="star" style="margin-bottom: 20px;">
	    <%= f.label :rate,'評価' %>
	    <%= f.hidden_field :rate, id: :review_star %>
	</div>
	<script>
		$("#star").raty({
            size     : 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            scoreName: 'post[rate]',
            half: true,
      });
	</script>

<!--ジャンル選択　-->
	<div class="field row" style="margin-bottom: 20px;">
		<div class="listing-form-box">
  			<div class="listing-post-detail__genre">
    			<%= f.label 'ジャンル', class: 'listing-default__label' %>
    			<div class="listing-select-wrapper">
      				<div class="listing-select-wrapper__box">
        				<%= f.select :genre_id, options_for_select(@genre_parent_array.map { |genre| [genre[:name], genre[:id]] }), {}, {class: 'listing-select-wrapper__box--select', id: 'parent_genre' } %>
      				</div>
    			</div>
			</div>
		</div>
	</div>

	<div class="field row" style="margin-bottom: 20px;">
		<i class="fas fa-map-marker-alt"></i>
		<%= f.text_field :title, :placeholder =>"--国名/都市名を入力してください--", class: "col-xs-12 post_title" %>
	</div>

	<div class="field row" style="margin-bottom: 20px;">
		<%= f.label :本文 %>
		<%= f.text_area :body, class: "col-xs-12 post_body" %>
	</div>

	<div class="field row" style="margin-bottom: 20px;">
		<select name="post[status]" id="post_status">
		  <option value="draft">下書き</option>
		  <option value="published">公開中</option>
		</select>
	</div>

	<div class="actions row" style="margin-bottom: 20px;">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/posts/_unclip.html.erb
<%= link_to post_clips_path(post.id), method: :delete, id: :"js-clip-button-for-post-#{post.id}" do %>
	<i class="fas fa-bookmark fa-2x"></i>
<% end %>

app/views/posts/clips.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-12" style="padding: 0;">

			<div class="row" style="padding-left: 100px;">
				<h2> Your Bookmark Posts</h2>
			</div>
			<!-- google map -->
			<div class="row" style="margin-top: 20px;">
				<div class="col-xs-10 col-xs-offset-1" style="padding: 0;">
					<div style="width: 100%;">
	  					<div id="map" style="width: 100%; height: 350px;"></div>
					</div>
					<script>
					  handler = Gmaps.build('Google');
					  handler.buildMap({
					    provider: {mapTypeId: 'roadmap'},
					    internal: {id: 'map'}
					    },
					    function(){
					    //markers = handler.addMarkers(#{raw @hash.to_json})
					    markers = handler.addMarkers(<%=raw @hash.to_json %>)
					    handler.bounds.extendWith(markers);
					    handler.fitMapToBounds();
					    handler.getMap().setCenter(new google.maps.LatLng(35.681298, 139.7640582));
					    handler.getMap().setZoom(1);
					  });
					</script>
				</div>
			</div>
			<!-- ブックマーク一覧 -->
			<div class="row" style="margin-top: 20px;">
				<% @posts.each do |post| %>
					<div class="col-xs-4">
						<div class="post-clip-box">
							<div class="row" style="margin: 10px;">
								<% post.post_images.first(1).each do |image| %>
									<%= link_to post_path(post.id) do %>
										<%= attachment_image_tag(image, :image, size:'340x220', class: "index-img") %>
									<% end %>
								<% end %>
							</div>
							<div class="row" style="margin: 10px;">

								<%= link_to (post.user) do %>
									<%= attachment_image_tag(post.user, :image, size:'40x40', fallback:"no_image.jpg") %>
								<% end %>
								<%= post.user.nick_name %>
							</div>
							<div class="row" style="margin: 10px;">
							<i class="fas fa-map-marker-alt"></i>  <%= link_to post.title, post, class: "post_#{post.id}" %>
							|
							<strong>Content: </strong><%= post.body %>
							</div>
						</div>
					</div>
				<% end %>
			</div>
			<div class="row pull-right">
			<%= paginate @posts %>
			</div>
		</div>
	</div>
</div>

app/views/posts/confirm.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-12">
			<h2>Draft Posts</h2>

			
			<% @posts.each do |post| %>
				<div class="row">
					<div class="col-xs-12" style="margin-top: 20px; border-bottom: 1px solid; border-color: silver;">

						<div class="row" style="margin: 10px;">
							<% post.post_images.each do |image| %>
								<%= attachment_image_tag(image, :image, size:'220x200') %>
							<% end %>
						</div>
						<div class="row" style="margin: 10px;">

							<%= link_to (post.user) do %>
								<%= attachment_image_tag(post.user, :image, size:'50x50', fallback:"no_image.jpg") %>
							<% end %>
							<%= post.user.nick_name %>
						</div>
						<div class="row" style="margin: 10px;">
							<strong>Title: </strong><%= link_to post.title, post, class: "post_#{post.id}" %>
							|
							<strong>Content: </strong><%= post.body %>
							|
						</div>
					</div>
				</div>
			<% end %>
			

		</div>
	</div>
</div>

app/views/posts/edit.html.erb
<div class="container">
	<%= render 'layouts/errors', model: @post %>

	<div class="row">
		<div class="col-xs-10 col-xs-offset-1">
			<h2 style="margin-bottom: 30px;">Edit Posts</h2>
				<%= render 'posts/new_form', post: @post %>
		</div>
	</div>
</div>

app/views/posts/hashtag.html.erb
<% provide(:title, @tag.hashname) %>
<div class="container">
	<div class="row">
		<div class="col-xs-10 col-xs-offset-1">
			<!-- ハッシュタグ名 -->
			<div class="row">
				<div class="col-xs-6 col-xs-offset-3">
					<h1><%= @tag.hashname %> : <%= @posts.count %>posts</h1>
				</div>
			</div>
			<!-- 投稿一覧 -->
			<div class="row" style="margin-top: 40px;">
				<% @posts.each do |post| %>
					<div class="col-xs-4">
						<div class="hash-box">
							<div class="row">
								<div class="col-xs-12">
									<% post.post_images.first(1).each do |image| %>
										<%= link_to post_path(post.id) do %>
											<%= attachment_image_tag(image, :image, size:'265x230', class: "hash-img") %>
										<% end %>
									<% end %>
								</div>
							</div>
							<div class="row" style="margin: 10px;">
								<div class="col-xs-12">
									<div class="col-xs-7" style="padding-top: 10px; padding-left: 0; margin: 0;">
										<div id="star-rate-<%= post.id %>"></div>
									</div>
									<div class="col-xs-4" style="color:silver; padding: 0; margin:0;">
										<h4 class="mb-3"><%= post.rate %></h4>
									</div>
					            	<script>
						            	$('#star-rate-<%= post.id %>').raty({
								            size: 36,
								            starOff:  '<%= asset_path('star-off.png') %>',
								            starOn : '<%= asset_path('star-on.png') %>',
								            starHalf: '<%= asset_path('star-half.png') %>',
								            half: true,
								            readOnly: true,
								            score: <%= post.rate %>,
						         		 });
						            </script>
		        				</div>
		        			</div>
							<div class="row" style="margin: 10px;">
								<div class="col-xs-12">
									<i class="fas fa-map-marker-alt"></i><%= post.title %>
									 | <%= render_with_hashtags(post.body) %>
								</div>
							</div>
						</div>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/posts/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-9">
			<div class="row" style="margin-top: 20px;">
				<% @posts.each do |post| %>
					<div class="col-xs-4">
						<!-- １件ずつの投稿ボックス -->
						<div class="post-box">
							<div class="row" style="margin: 10px;">
								<% post.post_images.first(1).each do |image| %>
									<%= link_to post_path(post.id) do %>
										<%= attachment_image_tag(image, :image, size:'235x200', class: "index-img") %>
									<% end %>
								<% end %>
							</div>
							<div class="row" style="margin: 10px;">
								<%= link_to (post.user) do %>
									<%= attachment_image_tag(post.user, :image, size:'40x40', fallback:"no_image.jpg") %>
								<% end %>
								<%= post.user.nick_name %>
							</div>
							<div class="row" style="margin: 10px;">
							<i class="fas fa-map-marker-alt"></i>  <%= link_to post.title, post, class: "post_#{post.id}" %>
							|
							<strong>Content: </strong><%= post.body %>
							</div>
						</div>
					</div>
				<% end %>
			</div>
			<div class="row pull-right">
				<%= paginate @posts %>
			</div>
		</div>
		<div class="col-xs-3" style="padding-left: 50px;">
			<h2 class="genres" style="padding-left: 50px;"><strong>ジャンル</strong></h2>
			<div class="row" style="margin-top: 20px;">
				<% @parents.each do |parent| %>
					<div class="row" style="margin-left: 10px; padding-bottom: 10px; padding-left: 50px;">
						<div class="col-xs-8" style="border-bottom: 1px solid silver;">
							<%= link_to genre_path(parent.id) do %>
								<h3><%= parent.name %> </h3>
							<% end %>
						</div>
					</div>
					<div class="row" style="margin-left: 10px; padding-left: 50px; margin-bottom: 20px;">
						<% parent.children.each do |child| %>
							<div class="col-xs-6">
								<%= link_to genre_path(child.id) do %>
									<h5><%= child.name %>(<%= child.posts.count %>)</h5>
								<% end %>
							</div>
						<% end %>
					</div>
				<% end %>
			</div>
			<h2 class="hashtags" style="padding-left: 50px; margin-top: 40px;"><strong>タグ</strong></h2>
			<div class="row" style="margin-top: 20px; margin-left: 40px;">
				<% @tag.first(15).sort.reverse.each do |tag| %>
					<div class="col-xs-6" style="padding-right: 0;">
						<%= link_to "/post/hashtag/#{tag.hashname}",data: {"turbolinks" => false} do %>
						<h4 style="margin-top: 8px;">#<%= tag.hashname %></h4>
						<% end %>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/posts/new.html.erb
<div class="container">
	<%= render 'layouts/errors', model: @post %>

	<div class="row">
		<div class="col-xs-10 col-xs-offset-1">
			<div class="row">
				<div class="col-xs-3">
					<h2 style="margin-bottom: 30px;">新規投稿</h2>
				</div>
			</div>

			<%= render 'posts/new_form', post: @post %>

			<div class="row" style="margin-top: 60px;">
				<div class="col-xs-3">
					<h2 style="margin-bottom: 10px;">下書き</h2>
				</div>
				<div class="col-xs-12">
					<%= render 'posts/confirm', posts: @posts %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/posts/ranking.html.erb
<div class="container">
	<div class="row">

		<div class="col-xs-8">
			<% @all_ranks.each.with_index(1) do |post, i| %>
				<div class="rank-box">
					<div class="row">
						<div class="col-xs-12">
							<div class="row" style="margin: 10px;">
								<h4 style="color: #ff7a91;">\ No.<%= i %> /</h4>
							</div>
							<div class="row" style="margin: 10px;">
								<div class="col-xs-6">
									<% post.post_images.first(1).each do |image| %>
										<%= attachment_image_tag(image, :image, size:'350x250') %>
									<% end %>
								</div>
								<div class="col-xs-6" style="padding-left: 30px;">
									<div class="row" style="margin: 10px;">
										<div class="content">
											<i class="fas fa-map-marker-alt"></i>  <%= link_to post.title, post, class: "post_#{post.id}" %>
										</div>
									</div>
									<div class="row" style="margin: 10px;">
										<div class="content">
											<strong>Content: </strong><%= render_with_hashtags(post.body) %>
										</div>
									</div>
									<div class="row" style="margin: 10px;">
										<div class="content">
											<strong>Genre: </strong><%= post.genre.name %>
										</div>
									</div>
									<div class="row" style="margin: 10px;">
										<%= link_to (post.user) do %>
											<%= attachment_image_tag(post.user, :image, size:'50x50', fallback:"no_image.jpg") %>
										<% end %>
										<%= post.user.nick_name %>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			<% end %>
		</div>

		<div class="col-xs-4" style="padding-left: 50px;">
			<h2 style="margin-left: 50px;"><strong>ジャンル</strong></h2>
			<div class="row" style="margin-top: 20px;">
				<% @parents.each do |parent| %>
					<div class="row" style="margin-left: 10px; padding-bottom: 10px; padding-left: 50px;">
						<div class="col-xs-8" style="border-bottom: 1px solid silver;">
							<%= link_to genre_path(parent.id) do %>
								<h3><%= parent.name %> </h3>
							<% end %>
						</div>
					</div>
					<div class="row" style="margin-left: 10px; padding-left: 50px; margin-bottom: 40px;">
						<% parent.children.each do |child| %>
							<div class="col-xs-6">
								<%= link_to genre_path(child.id) do %>
									<h5><%= child.name %>(<%= child.posts.count %>)</h5>
								<% end %>
							</div>
						<% end %>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/posts/show.html.erb
<div class="container" style="width: 100%;">
	<div class="row">
		<div class="col-xs-12">
			<!-- 投稿画像 -->
			<div class="row" style="padding-left: 30px;">
				<div class="col-xs-7">
					<div class="row">
						<% if @post.post_images.present? %>
							<!--スライドショー-->
							<div id="post-show">
								<div id="postShow">
									<% @post.post_images.each do |image| %>
										<div>
										<%= attachment_image_tag image, :image, class: "show-img" %>
										</div>
									<% end %>
								</div>
							</div>
						<% end %>
					</div>
					<div class="row">
						<div class="col-xs-1 pull-left">
							<!-- いいね　-->
							<% if user_signed_in? %>
								<% if @post.favorited_by?(current_user) %>
									<%= link_to post_favorites_path(@post), method: :delete do %>
										<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
										<%= @post.favorites.count %>
									<% end %>
								<% else %>
									<%= link_to post_favorites_path(@post), method: :post do %>
										<i class="fa fa-heart-o" aria-hidden="true"></i>
										<%= @post.favorites.count %>
									<% end %>
								<% end %>
							<% end %>
						</div>
						<!--　ブックマーク -->
			            <div class="col-xs-1 pull-left">
			            	<% if user_signed_in? %>
								<% if @post.user != current_user %>
									<% if @post.clip_by?(current_user) %>
									  	<%= render 'posts/unclip', post: @post %>
									<% else %>
								  		<%= render 'posts/clip', post: @post %>
									<% end %>
								<% end %>
							<% end %>
			            </div>
						<div class="col-xs-1 pull-right">
				        	<% if @post.user ==current_user %>
								<%= link_to edit_post_path do %>
									<i class="far fa-edit fa-2x fa-spin"></i>
								<% end %>
							<% end %>
						</div>
						<div class="col-xs-1 pull-right">
							<% if @post.user == current_user %>
								<%= link_to @post, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"} do%>
								<i class="far fa-trash-alt fa-2x"></i>
								<% end %>
							<% end %>
						</div>
					</div>
				</div>
				<div class="col-xs-1">
				</div>
				<div class="col-xs-3" style="padding-right: 0;">
					<div class="row">
						<!-- Google Map -->
						<div style="width: 100%;">
		  					<div id="map" style="width: 100%; height: 300px;"></div>
						</div>
						<script>
						  handler = Gmaps.build('Google');
						  handler.buildMap({
						    provider: {mapTypeId: 'roadmap'},
						    internal: {id: 'map'}
						    },
						    function(){
						    //markers = handler.addMarkers(#{raw @hash.to_json})
						    markers = handler.addMarkers(<%=raw @hash.to_json %>)
						    handler.bounds.extendWith(markers);
						    handler.fitMapToBounds();
						    handler.getMap().setCenter(new google.maps.LatLng);
						    handler.getMap().setZoom(1);
						  });
						</script>
					</div>
					<div class="row" style="margin-top: 30px;">
						<div class="clip-box-a">
							<div class="row" style="padding:5px 0 10px 20px;">
								<i class="fas fa-map-marker-alt"></i>  <%= @post.title %>
							</div>
							<div class="row" style="padding:5px 0 10px 20px;">
								<strong>Genre: </strong><%= @post.genre.name %>
							</div>
							<div class="row" style="padding:5px 0 10px 20px;">
								<strong>Content: </strong><%= render_with_hashtags(@post.body) %>
							</div>
							<!-- 評価 -->
							<div class="row" style="padding:3px 0 10px 5px;">
								<div class="col-xs-5" style="padding-top: 10px; padding-right: 0; margin: 0;">
									<div id="star-rate-<%= @post.id %>"></div>
								</div>
								<div class="col-xs-2" style="color:silver; padding: 10px 0 0 0; margin:0;">
									<h4 class="mb-3"><%= @post.rate %></h4>
								</div>
					            <script>
					            	$('#star-rate-<%= @post.id %>').raty({
							            size: 36,
							            starOff:  '<%= asset_path('star-off.png') %>',
							            starOn : '<%= asset_path('star-on.png') %>',
							            starHalf: '<%= asset_path('star-half.png') %>',
							            half: true,
							            readOnly: true,
							            score: <%= @post.rate %>,
					         		 });
					            </script>
					        </div>
					        <div class="row" style="padding:20px 0 0 20px;">
								<%= link_to (@post.user) do %>
									<%= attachment_image_tag(@post.user, :image, size:'50x50') %>
								<% end %>
								<%= @post.user.nick_name %>
							</div>
					    </div>
			        </div>
				</div>
			</div>
		</div>
	</div>
</div>